export const LOAD_ROUTES_REQUEST = 'search/LOAD_ROUTES_REQUEST';
export const LOAD_ROUTES_FAILURE = 'search/LOAD_ROUTES_FAILURE';
export const LOAD_ROUTES_SUCCESS = 'search/LOAD_ROUTES_SUCCESS';

export const LOAD_ROUTE_CONFIG_REQUEST = 'search/LOAD_ROUTE_CONFIG_REQUEST';
export const LOAD_ROUTE_CONFIG_FAILURE = 'search/LOAD_ROUTE_CONFIG_FAILURE';
export const LOAD_ROUTE_CONFIG_SUCCESS = 'search/LOAD_ROUTE_CONFIG_SUCCESS';

export const SELECTED_ROUTE = 'search/SELECTED_ROUTE';
export const SELECTED_DIRECTION = 'search/SELECTED_DIRECTION';
export const SELECTED_STOP = 'search/SELECTED_STOP';

export const CLEAR_ROUTE = 'search/CLEAR_ROUTE';
export const CLEAR_DIRECTION = 'search/CLEAR_DIRECTION';
export const CLEAR_STOP = 'search/CLEAR_STOP';
