export const LOAD_VEHICLE_LOCATION_REQUEST = 'vehicleLocation/LOAD_VEHICLE_LOCATION_REQUEST';
export const LOAD_VEHICLE_LOCATION_FAILURE = 'vehicleLocation/LOAD_VEHICLE_LOCATION_FAILURE';
export const LOAD_VEHICLE_LOCATION_SUCCESS = 'vehicleLocation/LOAD_VEHICLE_LOCATION_SUCCESS';

// export const CLEAR_VEHICLE_LOCATION = 'vehicleLocation/CLEAR_VEHICLE_LOCATION';
